parallel processing

diff --git a/Advanced_shell/batchProcessing-0x04 b/Advanced_shell/batchProcessing-0x04
--- a/Advanced_shell/batchProcessing-0x04
+++ b/Advanced_shell/batchProcessing-0x04
@@ -2,7 +2,9 @@
 
 pokemon_list=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")
 
+
 api_url="https://pokeapi.co/api/v2/pokemon/"
+
 
 fetch_pokemon_data() {
     local pokemon_name="$1"
@@ -18,11 +20,22 @@ fetch_pokemon_data() {
     fi
 }
 
+pids=()
+
 for pokemon in "${pokemon_list[@]}"; do
     fetch_pokemon_data "$pokemon" &
+    pids+=($!)
     sleep 1
 done
 
-wait
+for pid in "${pids[@]}"; do
+    wait $pid
+    if [[ $? -ne 0 ]]; then
+        echo "Process $pid failed. Killing process..."
+        kill $pid
+    fi
+done
+
+jobs
 
 echo "All requests completed."
